// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "bs-platform/lib/es6/curry.js";
import * as Belt_MutableStack from "bs-platform/lib/es6/belt_MutableStack.js";

function promisify(f, x) {
  return Promise.resolve(Curry._1(f, x));
}

function insert(t, a) {
  return Promise.resolve(Belt_MutableStack.push(t, a));
}

function make(x, param) {
  return x;
}

var Index = {
  make: make,
  next: Belt_MutableStack.pop
};

var MutableStackStorage = {
  make: Belt_MutableStack.make,
  insert: insert,
  Index: Index
};

export {
  promisify ,
  MutableStackStorage ,
  
}
/* No side effect */
